### ISSUE TITLE
Not working on glyphs

### ISSUE THREAD

**Issue by oisatsuki** [yanone/speedpunk#6]
Hello! I am having a bit of trouble to use Speedpunk. 
It was working before and now suddenly it doesn't show on the view menu anymore, neither the cmnd + shift + x works. 

![image](https://user-images.githubusercontent.com/70924300/103010493-345ce680-4517-11eb-8348-5c8772b335c1.png)

I wonder if this was supposed to be it: 
![image](https://user-images.githubusercontent.com/70924300/103010539-450d5c80-4517-11eb-9df0-9a5107187a02.png)

Anyway, I've searched for solutions, uninstalled and installed again and nothing worked yet. What should I do? My version of Glyphs is 2.6.6

**Comment by yanone** [comment]
Sorry for the late reply.
I have just tried with Glyphs 2.6.5 (the stable version), and can confirm that the plugin works as expected.

Since Speed Punk got open-sourced, the Glyphs team is also fixing bugs. It's possible that the bug has been fixed in the meantime.

So I would like to ask you to try again by uninstalling and reinstalling (don't forget to restart Glyphs). If it still doesn't work, please see if you can find an error message in the lower part of the Macro window and paste it here.

**Comment by schriftgestalt** [comment]
It works for me in 2.6.5 and 2.6.6. What version of macOS do you have?

**Comment by oisatsuki** [comment]
Sorry for the very late reply, it's working fine now! Thanks for the help
